---
- name: Create and Copy public ssh key of Ansible Control Node
  hosts: localhost
  
  vars:
    - username: pajeca

  tasks:
    - name: Create public ssh key in Ansible Control Node
      community.crypto.openssh_keypair:
        path: /home/{{ username }}/.ssh/id_ed25519
        type: ed25519

    - name: Copy public ssh key of Ansible Control Node
      command: 'cat /home/{{ username }}/.ssh/id_ed25519.pub'
      register: public_key

- name: Copy public ssh certificate from Ansible Control Node to hosts
  hosts:  all

  vars: 
    - username: pajeca

  tasks:
    - name: Create .ssh dir
      file:
        path: '/home/{{ username }}/.ssh'
        state: directory

    - name: Create authorized_keys file
      file: 
        path: '/home/{{ username }}/.ssh/authorized_keys'
        state: touch
        owner: '{{ username }}'
        mode: '600'

    - name: Copy public key into authorized keys file
      lineinfile:
        path: '/home/{{ username }}/.ssh/authorized_keys'
        line: "{{ hostvars['localhost']['public_key']['stdout'] }}"
